site_name: Teams app camp
site_url: https://microsoft.github.io/app-camp
nav: 
- Home: 'index.md'
- Prerequisites: 'https://github.com/microsoft/app-camp/wiki/Prerequisites'
- Core app lab(path A): 
  - Start with Azure Active Directory: 'aad/A01-begin-app.md'
  - Create a Teams app with Azure AD Teams SSO: 'aad/A02-after-teams-sso.md'
  - Teams styling and themes: 'aad/A03-after-apply-styling.md'
- Core app lab(path B): 
  - Start with a non-Azure Active Directory Identity System: 'bespoke/B01-begin-app.md'
  - Teams App with Bespoke Authentication: 'bespoke/B02-after-teams-login.md'
  - Enable Azure AD Single Sign-On: 'bespoke/B03-after-teams-sso.md'
  - Teams styling and themes: 'bespoke/B04-after-apply-styling.md'
- More app capabilities:
  - Add a configurable tab: 'aad/ConfigurableTab.md'
  - Add a Deep link to a personal Tab: 'aad/Deeplink.md'
  - Add a Messaging Extension: 'aad/MessagingExtension.md'
  - Add a Task Module: 'aad/TaskModules.md'
  - Selling Your SaaS-based Teams Extension: 'aad/Monetization.md'
- Resources:
  - Find all resources: 'Resources.md'
theme:
  name: 'material'
  palette: 
    primary: 'brown'
    accent: 'deep orange'
  logo: 'assets/code-lab-banner-transparent.png'
  features:
        - navigation.tabs